import type { IntlCaseText } from "@/lib/content-types";

export const part: Record<string, IntlCaseText> = {
  "maejo-topload-2-2569-08": {
    title: "Strip-down clean of a second top loader in Mae Jo: blackened pulsator base and scale in the outer tub",
    service: "Washing machine cleaning",
    area: "Mae Jo, San Sai, Chiang Mai",
    equipment: "Top-load washing machine",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The pulsator base and centre shaft had black deposits built up so thick they had formed sheets. The floor of the outer tub was covered in brown scale all the way round, and the plastic tub rim had buildup along its grooves.",
    actions: ["Tested the machine before dismantling it","Removed the pulsator, inner tub and tub rim to clean them separately","Scrubbed the black deposits off the pulsator base and the scale off the outer tub floor","Cleaned the tub rim and the parts around the tub","Reassembled, levelled the machine and ran a test cycle"],
    result: "The stainless tub is shiny, the pulsator and the outer tub floor are white again, and the tub rim has no buildup left in its grooves",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on the shop's washing-machine page and show the same machine throughout (a different machine from the Samsung case in Mae Jo on the same day)",
    alts: ["Washing machine cleaning, 24 August 2026, before cleaning, photo 1","Washing machine cleaning, 24 August 2026, before cleaning, photo 2","Washing machine cleaning, 24 August 2026, before cleaning, photo 3","Washing machine cleaning, 24 August 2026, after cleaning, photo 1","Washing machine cleaning, 24 August 2026, after cleaning, photo 2","Washing machine cleaning, 24 August 2026, after cleaning, photo 3","Washing machine cleaning, 24 August 2026, after cleaning, photo 4"],
  },
  "lg-smart-inverter-topload-2569-07": {
    title: "LG Smart Inverter top-loader strip-down clean: rust on the outside of the tub, buildup on the outer tub floor and in the detergent compartments",
    service: "Washing machine cleaning",
    area: "Chiang Mai",
    equipment: "LG Smart Inverter top-load washing machine",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "Lifting out the inner tub revealed long streaks of brown rust on the outer surface of the stainless tub. Brown deposits had collected around the shaft on the outer tub floor, all three detergent and powder compartments were coated in thick black grime, and the base under the pulsator had rust and buildup between its ribs.",
    actions: ["Tested the machine, then removed the top cover and the detergent compartments first","Lifted the stainless tub out of the outer tub","Removed the pulsator and scrubbed its base and the centre shaft","Cleaned the outer tub floor, the detergent compartments and the lint filter","Reassembled, levelled the machine and ran a test cycle"],
    result: "All three detergent compartments and the filter are clean and white again, no brown deposits remain on the outer tub floor, and the top of the pulsator is clean and ready to go back in",
    recorded: "11 Jul 2026",
    sourceNote: "All photos come from the same post on the shop's washing-machine page and show the same machine throughout. The third pair compares opposite sides of the pulsator (the underside before cleaning and the top face after cleaning)",
    alts: ["Washing machine cleaning, 11 July 2026, before cleaning, photo 1","Washing machine cleaning, 11 July 2026, before cleaning, photo 2","Washing machine cleaning, 11 July 2026, before cleaning, photo 3","Washing machine cleaning, 11 July 2026, before cleaning, photo 4","Washing machine cleaning, 11 July 2026, before cleaning, photo 5","Washing machine cleaning, 11 July 2026, during cleaning, photo 1","Washing machine cleaning, 11 July 2026, after cleaning, photo 1","Washing machine cleaning, 11 July 2026, after cleaning, photo 2","Washing machine cleaning, 11 July 2026, after cleaning, photo 3"],
  },
  "saraphi-daikin-install-2569-05": {
    title: "New Daikin installation in Saraphi: from the box to a unit on the wall",
    service: "Aircon installation",
    area: "Saraphi District, Chiang Mai",
    equipment: "Daikin wall-mounted aircon, new in the box",
    reportedIssue: "No symptoms recorded; this was a new-unit installation",
    finding: "The site was a bare wall with no mounting points yet. I started by holding the mounting plate in place and checking the level, drilled through the wall to run the pipes and pipe trunking, and only then lifted the indoor unit into place. The outdoor unit went on a wall bracket outside the house.",
    actions: ["Positioned the mounting plate and checked the level for the indoor unit","Drilled the wall and ran the refrigerant pipes inside trunking","Fitted the bracket and the outdoor unit outside the house","Connected the pipes, pulled a vacuum and ran a test"],
    result: "The indoor unit is level, the trunking runs in a straight line down to the outdoor unit, and the remote wiring has been neatly finished",
    recorded: "30 May 2026",
    sourceNote: "All photos come from the same post on the shop's aircon page and show the same house throughout",
    alts: ["Aircon installation, 30 May 2026, during installation, photo 1","Aircon installation, 30 May 2026, before installation, photo 1","Aircon installation, 30 May 2026, during installation, photo 2","Aircon installation, 30 May 2026, after installation, photo 1","Aircon installation, 30 May 2026, after installation, photo 2"],
  },
  "midea-chione-install-2569-06": {
    title: "New Midea Chione installation: indoor unit above a glass door, outdoor unit on the front of the house",
    service: "Aircon installation",
    area: "Chiang Mai",
    equipment: "Midea Chione wall-mounted aircon, 1 new set",
    reportedIssue: "No symptoms recorded; this was a new-unit installation",
    finding: "The aircon arrived on site in two boxes. I unpacked them and checked the parts on the balcony floor first, then lifted the indoor unit onto its mounting plate above the glass door. For the outdoor unit, I drilled and fixed a bracket on the front wall of the house.",
    actions: ["Unpacked and checked that all parts were present before installing","Fixed the mounting plate and hung the indoor unit above the glass door","Drilled and fixed the bracket, then set the outdoor unit on the wall","Connected the refrigerant pipes, pulled a vacuum and ran a test"],
    result: "The indoor unit is level with the pipes running straight out the back, and the outdoor unit sits firmly on its bracket with the insulated pipes dressed in a single run",
    recorded: "6 Jun 2026",
    sourceNote: "All photos come from the same post on the shop's aircon page and show the same house throughout",
    alts: ["Aircon installation, 6 June 2026, before installation, photo 1","Aircon installation, 6 June 2026, during installation, photo 1","Aircon installation, 6 June 2026, during installation, photo 2","Aircon installation, 6 June 2026, during installation, photo 3","Aircon installation, 6 June 2026, after installation, photo 1","Aircon installation, 6 June 2026, during installation, photo 4"],
  },
  "midea-new-unit-install-2569-06": {
    title: "New Midea set installed: outdoor unit stacked on the same wall as another unit",
    service: "Aircon installation",
    area: "Chiang Mai",
    equipment: "Midea Chione wall-mounted aircon, 1 new set (indoor unit box and outdoor unit box)",
    reportedIssue: "No symptoms recorded; this was a new-unit installation",
    finding: "The indoor unit box, the outdoor unit box, the refrigerant pipes and the trunking were all ready on site. The new outdoor unit went on a bracket stacked with another unit on the same wall, so the trunking could follow a single run.",
    actions: ["Unpacked and prepared the refrigerant pipes and trunking","Mounted the indoor unit on the room wall","Fitted the bracket and set the outdoor unit on the front wall of the house","Connected the pipes, pulled a vacuum and ran a test"],
    result: "The indoor unit is installed in the room, the outdoor unit is on the same wall as the other unit, and the trunking follows a single run",
    recorded: "19 Jun 2026",
    sourceNote: "Photos come from the job post of 19 Jun 2026, in which the shop reported installing 1 new aircon, cleaning 1 aircon, removing 1 aircon with its refrigerant recovered and cleaning 1 washing machine. This case uses only the installation photos.",
    alts: ["Aircon installation, 19 June 2026, before installation, photo 1","Aircon installation, 19 June 2026, before installation, photo 2","Aircon installation, 19 June 2026, before installation, photo 3","Aircon installation, 19 June 2026, during installation, photo 1","Aircon installation, 19 June 2026, after installation, photo 1","Aircon installation, 19 June 2026, after installation, photo 2","Aircon installation, 19 June 2026, during installation, photo 2"],
  },
  "tha-wang-tan-lg-relocate-2569-06": {
    title: "LG aircon relocation in Tha Wang Tan: taken down from the old spot and installed on a new wall",
    service: "Aircon relocation",
    area: "Tha Wang Tan, Saraphi District",
    equipment: "The customer's existing LG wall-mounted aircon",
    reportedIssue: "No symptoms recorded; this job was moving an existing unit to a new position",
    finding: "The new wall had only a wall fan on it. The indoor unit and its mounting plate had been taken down and set on the ground in front of the house, and the outdoor unit bracket had been fixed in advance under the eaves beside a window.",
    actions: ["Removed the indoor and outdoor units from their old positions","Fitted the mounting plate and the indoor unit on the new wall","Lifted the outdoor unit onto the bracket under the eaves","Ran new pipes, pulled a vacuum and ran a test"],
    result: "The indoor unit is on its new wall above the window, the outdoor unit is on its bracket under the eaves, and the pipes and cables are neatly routed into the wall",
    recorded: "19 Jun 2026",
    sourceNote: "All photos come from the same post on the shop's aircon page and show the same unit and the same house throughout",
    alts: ["Aircon relocation, 19 June 2026, before relocation, photo 1","Aircon relocation, 19 June 2026, during relocation, photo 1","Aircon relocation, 19 June 2026, after relocation, photo 1","Aircon relocation, 19 June 2026, during relocation, photo 2","Aircon relocation, 19 June 2026, after relocation, photo 2","Aircon relocation, 19 June 2026, before relocation, photo 2","Aircon relocation, 19 June 2026, after relocation, photo 3"],
  },
  "nong-pa-khrang-ceiling-unit-check-2569-06": {
    title: "Electrical check and clean of a ceiling-suspended aircon in Nong Pa Khrang: outdoor unit on the roof",
    service: "Aircon repair",
    area: "Nong Pa Khrang, Mueang Chiang Mai District",
    equipment: "Season ceiling-suspended aircon with its outdoor unit on the roof",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The ceiling-suspended unit had buildup across its front panel, louvers and filters. The outdoor unit on the roof had dust and black grime on its top cover. I opened up the outdoor unit and took electrical readings first, then cleaned the whole system.",
    actions: ["Opened the outdoor unit on the roof and took electrical readings","Removed the front panel, louvers and filters of the ceiling-suspended unit","Washed the outdoor unit and its grille","Reassembled and ran a test"],
    result: "The top cover and grille of the outdoor unit are clean again, and the front panel and louvers were washed until no dust was left between the slats",
    recorded: "26 Jun 2026",
    sourceNote: "All photos come from the same post on the shop's aircon page and show the same unit throughout",
    alts: ["Aircon repair, 26 June 2026, before repair, photo 1","Aircon repair, 26 June 2026, after repair, photo 1","Aircon repair, 26 June 2026, before repair, photo 2","Aircon repair, 26 June 2026, before repair, photo 3","Aircon repair, 26 June 2026, during repair, photo 1","Aircon repair, 26 June 2026, after repair, photo 2","Aircon repair, 26 June 2026, after repair, photo 3","Aircon repair, 26 June 2026, after repair, photo 4","Aircon repair, 26 June 2026, before repair, photo 4"],
  },
  "mueang-sharp-gauge-check-wash-2569-05": {
    title: "Special strip-down clean of a Sharp aircon in Mueang Chiang Mai after the customer reported water dripping",
    service: "Premium aircon cleaning (strip-down)",
    area: "Mueang Chiang Mai District",
    equipment: "Sharp wall-mounted aircon",
    reportedIssue: "The customer reported that the aircon was dripping water even though it had been cleaned not long before",
    finding: "The fan wheel, evaporator coil and unit frame were coated in thick black dust, and the outdoor coil had dust across its fins. I also connected a refrigerant pressure gauge to check the system.",
    actions: ["Connected a refrigerant pressure gauge to check the system","Took out the evaporator coil and fan wheel and cleaned them separately, piece by piece","Washed the outdoor coil","Reassembled and ran a test"],
    result: "The outdoor coil fins are clean enough to see the bare aluminium, the unit frame is free of black grime, and every part was cleaned before reassembly",
    recorded: "3 May 2026",
    sourceNote: "Photos come from the job post for a premium special strip-down clean of 1 unit on 3 May 2026. The whole post covers a single unit.",
    alts: ["Premium aircon cleaning (strip-down), 3 May 2026, before cleaning, photo 1","Premium aircon cleaning (strip-down), 3 May 2026, before cleaning, photo 2","Premium aircon cleaning (strip-down), 3 May 2026, after cleaning, photo 1","Premium aircon cleaning (strip-down), 3 May 2026, before cleaning, photo 3","Premium aircon cleaning (strip-down), 3 May 2026, during cleaning, photo 1","Premium aircon cleaning (strip-down), 3 May 2026, during cleaning, photo 2","Premium aircon cleaning (strip-down), 3 May 2026, after cleaning, photo 2","Premium aircon cleaning (strip-down), 3 May 2026, after cleaning, photo 3","Premium aircon cleaning (strip-down), 3 May 2026, after cleaning, photo 4"],
  },
  "mueang-four-units-wash-2569-06": {
    title: "Cleaning 4 aircons in Mueang Chiang Mai: filters and fan wheels before and after",
    service: "Aircon cleaning",
    area: "Mueang Chiang Mai District",
    equipment: "4 wall-mounted aircons",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The filters were so thick with dust that the mesh could not be seen, and the fan wheels had black grime built up between their blades.",
    actions: ["Laid down a tarp and fitted a drain bag under the unit","Removed the front panel and filters for washing","Washed the fan wheel in a separate tub","Washed the evaporator coil, reassembled and ran a test"],
    result: "The filters are see-through again and back to their original colour, and every unit was reassembled and ready to use",
    recorded: "26 Jun 2026",
    sourceNote: "Photos come from the job post for cleaning 4 aircons on 26 Jun 2026. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 26 June 2026, before cleaning, photo 1","Aircon cleaning, 26 June 2026, before cleaning, photo 2","Aircon cleaning, 26 June 2026, during cleaning, photo 1","Aircon cleaning, 26 June 2026, during cleaning, photo 2","Aircon cleaning, 26 June 2026, after cleaning, photo 1","Aircon cleaning, 26 June 2026, after cleaning, photo 2","Aircon cleaning, 26 June 2026, after cleaning, photo 3","Aircon cleaning, 26 June 2026, after cleaning, photo 4"],
  },
  "beko-wall-wash-2569-06": {
    title: "Cleaning 5 wall-mounted aircons in one job, including a Beko: filters, indoor coils and outdoor coils before and after",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "5 wall-mounted aircons, including a Beko",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The filters had dust caked on in sheets, the face of the evaporator coil had black dust, and the outdoor coil fins had grey dust over the whole surface.",
    actions: ["Laid down a tarp and fitted a drain bag under the unit","Removed the front panel and filters for washing","Washed the evaporator coil and fan wheel with the unit on the wall","Washed the outdoor coil, reassembled and ran a test"],
    result: "The filters are see-through again, the indoor and outdoor coil fins are cleaner, and the units are reassembled and ready to use",
    recorded: "6 Jun 2026",
    sourceNote: "Photos come from the job post for cleaning 5 wall-mounted aircons on 6 Jun 2026. The shop posted this job as a standard clean. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 6 June 2026, before cleaning, photo 1","Aircon cleaning, 6 June 2026, before cleaning, photo 2","Aircon cleaning, 6 June 2026, before cleaning, photo 3","Aircon cleaning, 6 June 2026, after cleaning, photo 1","Aircon cleaning, 6 June 2026, before cleaning, photo 4","Aircon cleaning, 6 June 2026, after cleaning, photo 2","Aircon cleaning, 6 June 2026, after cleaning, photo 3","Aircon cleaning, 6 June 2026, after cleaning, photo 4","Aircon cleaning, 6 June 2026, before cleaning, photo 5","Aircon cleaning, 6 June 2026, before cleaning, photo 6","Aircon cleaning, 6 June 2026, after cleaning, photo 5"],
  },
  "mitsubishi-mr-slim-wash-2569-06": {
    title: "Mitsubishi Mr.Slim aircon clean: evaporator coil and blower before and after",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Mitsubishi Electric Mr.Slim wall-mounted aircon",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The face of the evaporator coil had black dust and patchy grime, the blower wheel had dust in its grooves, and the outdoor coil fins had dust across the whole panel.",
    actions: ["Laid down a tarp and fitted a drain bag under the unit","Removed the front panel and filters for washing","Washed the evaporator coil and fan wheel with the unit on the wall","Washed the outdoor coil, reassembled and ran a test"],
    result: "The evaporator coil face is evenly clean across the whole panel, the blower wheel is glossy with no dust in its grooves, and the outdoor unit cover has been neatly refitted",
    recorded: "6 Jun 2026",
    sourceNote: "Photos come from the job post for cleaning 5 wall-mounted aircons on 6 Jun 2026 (the same post as the Beko case). The job was a standard clean.",
    alts: ["Aircon cleaning, 6 June 2026, before cleaning, photo 1","Aircon cleaning, 6 June 2026, after cleaning, photo 1","Aircon cleaning, 6 June 2026, before cleaning, photo 2","Aircon cleaning, 6 June 2026, during cleaning, photo 1","Aircon cleaning, 6 June 2026, after cleaning, photo 2","Aircon cleaning, 6 June 2026, after cleaning, photo 3","Aircon cleaning, 6 June 2026, after cleaning, photo 4","Aircon cleaning, 6 June 2026, after cleaning, photo 5"],
  },
  "lg-dual-inverter-wash-2569-06": {
    title: "Cleaning an LG Dual Inverter aircon and the outdoor unit of another aircon in the same job",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "LG Dual Inverter wall-mounted aircon and another aircon in the same job",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The LG evaporator coil had grey dust across the whole panel, dulling its colour. The outdoor unit of the other aircon had black dust filling its grille.",
    actions: ["Laid a tarp to catch water and removed the front panel and filters","Washed the LG evaporator coil","Washed the outdoor coil of the second unit","Reassembled and ran a test on both units"],
    result: "The LG evaporator fins are an even deep blue again, and the fins behind the other unit's outdoor grille are clearly visible across the whole panel",
    recorded: "19 Jun 2026",
    sourceNote: "Photos come from the job post for cleaning 3 aircons on 19 Jun 2026. Before and after photos were not paired across different units.",
    alts: ["Aircon cleaning, 19 June 2026, before cleaning, photo 1","Aircon cleaning, 19 June 2026, before cleaning, photo 2","Aircon cleaning, 19 June 2026, after cleaning, photo 1","Aircon cleaning, 19 June 2026, after cleaning, photo 2","Aircon cleaning, 19 June 2026, after cleaning, photo 3","Aircon cleaning, 19 June 2026, after cleaning, photo 4"],
  },
  "san-kamphaeng-midea-multi-wash-2569-06": {
    title: "Cleaning 4 aircons in San Kamphaeng: washing the evaporator coils on the wall, one unit at a time",
    service: "Aircon cleaning",
    area: "San Kamphaeng District, Chiang Mai",
    equipment: "4 Midea wall-mounted aircons",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "With the front panels off, the evaporator fins of every unit had black dust across the whole coil, and the filters had dust filling the mesh.",
    actions: ["Laid a tarp to catch water and removed the front panel, filters and louvers","Washed the evaporator coils on the wall, one unit at a time","Washed the filters and front panels","Reassembled and ran a test on every unit"],
    result: "The evaporator fins are cleaner across the whole coil, and every unit was reassembled on the wall and ready to use",
    recorded: "26 Jun 2026",
    sourceNote: "Photos come from the job post for cleaning 4 aircons on 26 Jun 2026, which was location-tagged San Kamphaeng District. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 26 June 2026, during cleaning, photo 1","Aircon cleaning, 26 June 2026, before cleaning, photo 1","Aircon cleaning, 26 June 2026, before cleaning, photo 2","Aircon cleaning, 26 June 2026, before cleaning, photo 3","Aircon cleaning, 26 June 2026, during cleaning, photo 2","Aircon cleaning, 26 June 2026, after cleaning, photo 1","Aircon cleaning, 26 June 2026, after cleaning, photo 2","Aircon cleaning, 26 June 2026, after cleaning, photo 3"],
  },
  "foam-coil-wash-2569-05": {
    title: "Wall-mounted aircon clean with foam over the coil: outdoor coil, filters and fan wheel before and after",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "3 wall-mounted aircons",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The outdoor coil fins had a layer of dust, the filters had dust caked on in sheets, and the blower wheel had black dust in its grooves. I sprayed cleaning foam over the whole evaporator coil so it could lift the dust before rinsing with water.",
    actions: ["Laid down a tarp and fitted a drain bag under the unit","Removed the front panel and filters for washing","Covered the evaporator fins with foam, then rinsed them with water","Washed the outdoor coil, reassembled and ran a test"],
    result: "The outdoor coil fins are clean enough to show the aluminium, both filters are see-through, and the fan wheel is clean with no dust in its grooves",
    recorded: "30 May 2026",
    sourceNote: "Photos come from the job post for cleaning 3 wall-mounted aircons on 30 May 2026. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 30 May 2026, before cleaning, photo 1","Aircon cleaning, 30 May 2026, before cleaning, photo 2","Aircon cleaning, 30 May 2026, before cleaning, photo 3","Aircon cleaning, 30 May 2026, after cleaning, photo 1","Aircon cleaning, 30 May 2026, during cleaning, photo 1","Aircon cleaning, 30 May 2026, after cleaning, photo 2","Aircon cleaning, 30 May 2026, after cleaning, photo 3","Aircon cleaning, 30 May 2026, after cleaning, photo 4"],
  },
  "mueang-samsung-wash-2569-05": {
    title: "Samsung aircon clean: evaporator base and drain channel before and after",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Samsung wall-mounted aircon",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The evaporator fins had black dust across the whole coil. The base and drain channel under the coil had long streaks of yellow and black buildup, and the channel at the side of the unit was packed with black grime.",
    actions: ["Laid a tarp to catch water and removed the front panel, filters and louvers","Washed the evaporator fins and the drain channel","Washed the front panel, filters and grille","Reassembled and ran a test"],
    result: "The base and drain channel are back to clean white plastic, the filters and front panel are clean, and the unit is neatly reassembled on the wall",
    recorded: "15 May 2026",
    sourceNote: "Photos come from the job post for a standard clean of 3 aircons on 15 May 2026. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 15 May 2026, before cleaning, photo 1","Aircon cleaning, 15 May 2026, after cleaning, photo 1","Aircon cleaning, 15 May 2026, before cleaning, photo 2","Aircon cleaning, 15 May 2026, before cleaning, photo 3","Aircon cleaning, 15 May 2026, after cleaning, photo 2","Aircon cleaning, 15 May 2026, after cleaning, photo 3","Aircon cleaning, 15 May 2026, after cleaning, photo 4","Aircon cleaning, 15 May 2026, after cleaning, photo 5"],
  },
  "haier-outdoor-coil-wash-2569-05": {
    title: "Cleaning 3 aircons at 3 homes: clogged outdoor unit grilles before and after",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "3 wall-mounted aircons at 3 homes, including a Haier outdoor unit",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "The grille on the front of the outdoor unit was so packed with dust that almost every opening had turned solid black, so less air could pass through the condenser coil. Indoors, the evaporator unit had black grime along its frame and drain pan.",
    actions: ["Inspected the outdoor unit grille and fins","Removed the indoor unit's front panel and filters for washing","Washed the outdoor coil until the fins were clear","Reassembled and ran a test"],
    result: "The outdoor unit grille is open again, so the fan inside can be seen, and the filters are clear across the whole sheet",
    recorded: "4 May 2026",
    sourceNote: "Photos come from the job post for a standard clean of 3 aircons on 4 May 2026, at 3 homes in different housing estates, one unit per home, so the photos in this case may come from different homes. Before and after photos were not paired across different units.",
    alts: ["Aircon cleaning, 4 May 2026, before cleaning, photo 1","Aircon cleaning, 4 May 2026, before cleaning, photo 2","Aircon cleaning, 4 May 2026, before cleaning, photo 3","Aircon cleaning, 4 May 2026, after cleaning, photo 1","Aircon cleaning, 4 May 2026, before cleaning, photo 4"],
  },
  "toshiba-inverter-wash-2569-05": {
    title: "Toshiba Inverter aircon clean: an evaporator coil black across the whole panel, clean again",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Toshiba Inverter wall-mounted aircon",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "With the cover off, the evaporator fins were black across almost the entire coil, and the drain pan and internal frame had black buildup. The outdoor unit grille outside the house was also clogged with dust in every opening.",
    actions: ["Laid a tarp to catch water and covered the area under the unit","Removed the front panel, filters and drain pan","Washed the evaporator coil until the water running off was clear","Washed the outdoor unit outside the house, then reassembled and tested"],
    result: "The evaporator fins are an even silver again, the frame and drain pan are clean, and the unit is back on the wall and ready to use",
    recorded: "4 May 2026",
    sourceNote: "Photos come from the job post for a standard clean of 3 aircons on 4 May 2026, at 3 homes in different housing estates, so some photos may show another unit from the same job.",
    alts: ["Aircon cleaning, 4 May 2026, during cleaning, photo 1","Aircon cleaning, 4 May 2026, after cleaning, photo 1","Aircon cleaning, 4 May 2026, before cleaning, photo 1","Aircon cleaning, 4 May 2026, after cleaning, photo 2"],
  },
  "shophouse-lg-wash-2569-05": {
    title: "Shophouse aircon clean: outdoor unit on the awning and indoor unit in the room",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "LG wall-mounted aircon with a Star-Aire outdoor unit",
    reportedIssue: "No symptoms from the customer were recorded in the post",
    finding: "At this shophouse the outdoor unit sits on the second-floor awning, so a ladder had to be set up from the footpath to work on it. The outdoor unit's front grille was packed with black dust, and the indoor unit's frame had black grime in its grooves.",
    actions: ["Set up the ladder and made sure of a secure footing before climbing onto the awning","Took the front panel, filters and indoor unit parts down for washing","Washed the outdoor coil on the awning","Reassembled and ran a test"],
    result: "The outdoor unit grille is open again, and the indoor unit's frame and parts were all cleaned before it was reassembled on the wall",
    recorded: "30 May 2026",
    sourceNote: "Photos come from the job post for cleaning 5 aircons on 30 May 2026. The photos in this case may come from several units in the same job.",
    alts: ["Aircon cleaning, 30 May 2026, after cleaning, photo 1","Aircon cleaning, 30 May 2026, after cleaning, photo 2","Aircon cleaning, 30 May 2026, before cleaning, photo 1","Aircon cleaning, 30 May 2026, after cleaning, photo 3","Aircon cleaning, 30 May 2026, before cleaning, photo 2","Aircon cleaning, 30 May 2026, after cleaning, photo 4","Aircon cleaning, 30 May 2026, during cleaning, photo 1","Aircon cleaning, 30 May 2026, after cleaning, photo 5"],
  },
  "saraphi-outdoor-relocate-2569-05": {
    title: "Taking down and relocating an outdoor unit in Saraphi: from a high wall down to a new spot",
    service: "Aircon relocation",
    area: "Saraphi District, Chiang Mai",
    equipment: "Outdoor unit of the customer's existing wall-mounted aircon",
    reportedIssue: "No symptoms recorded; this job was moving an existing unit to a new position",
    finding: "The outdoor unit was mounted high on the wall under the eaves. It had to come down by ladder, one step at a time, so the refrigerant pipes would not kink. Once it was off, the old wall was left with bracket marks and rust stains that needed tidying before the unit went up in its new spot.",
    actions: ["Pumped the refrigerant down into the compressor before disconnecting the pipes","Brought the outdoor unit down from the high wall using a ladder, with a helper below to receive it","Tidied the old wall and fitted a bracket in the new spot","Connected the pipes, pulled a vacuum and ran a test"],
    result: "The outdoor unit has been moved down onto a bracket in a new spot that is easier to reach than before, and the old wall has been neatly tidied",
    recorded: "30 May 2026",
    sourceNote: "All photos come from the same post on the shop's aircon page and show the same house throughout",
    alts: ["Aircon relocation, 30 May 2026, during relocation, photo 1","Aircon relocation, 30 May 2026, after relocation, photo 1","Aircon relocation, 30 May 2026, during relocation, photo 2","Aircon relocation, 30 May 2026, during relocation, photo 3","Aircon relocation, 30 May 2026, during relocation, photo 4","Aircon relocation, 30 May 2026, after relocation, photo 2"],
  },
};
