import type { IntlCaseText } from "@/lib/content-types";

export const part: Record<string, IntlCaseText> = {
  "top-load-washer-pulsator-deposit": {
    title: "Top-load washing machine strip-down clean: deposits under the pulsator",
    service: "Washing machine cleaning",
    area: "Chiang Mai",
    equipment: "Top-load washing machine, brand not clearly visible",
    reportedIssue: "No symptoms were recorded from the customer, so we do not conclude that there was an odour or residue on clothes.",
    finding: "With the pulsator removed, brown deposits were found built up around the spin shaft and along the grooves underneath.",
    actions: ["Test-ran the machine before dismantling", "Removed the pulsator to open up the area beneath it", "Scrubbed deposits out of the grooves and around the shaft", "Reassembled and ran the machine to check for leaks"],
    result: "After cleaning, the plastic surfaces and grooves of the pulsator are clearly visible again.",
    recorded: "2026",
    sourceNote: "The before and after photos were checked and confirmed to be the same machine and the same job.",
    lesson: [
      { t: "The built-in tub-clean programme doesn't reach under the pulsator", d: "The tub-clean programme swirls water around inside the inner tub, so it only helps the surfaces the water touches. The area under the pulsator and around the spin shaft is an enclosed space with very little water flowing through it, so deposits build up there and never get flushed away." },
      { t: "Odours on washed clothes usually come from places you can't see", d: "When clothes still smell musty after washing, it usually isn't the detergent or fabric softener. It comes from biological deposits clinging to the hidden side of the tub and under the pulsator." },
      { t: "How a strip-down clean differs from a cleaning-solution wash", d: "A strip-down clean means lifting the inner tub out and scrubbing it inside and out, removing the pulsator to clean its base, then reassembling and testing. Pouring cleaning solution in and running a cycle only cleans the surfaces the water reaches. One does not replace the other." },
    ],
    alts: ["Washing machine cleaning, before cleaning, photo 1", "Washing machine cleaning, after cleaning, photo 1"],
  },
  "front-load-washer-outer-tub-scale": {
    title: "Front-load washing machine strip-down clean: scale inside the outer tub",
    service: "Washing machine cleaning",
    area: "Chiang Mai",
    equipment: "Front-load washing machine, brand not clearly visible",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "Once the tub was opened up, brown streaks of scale were found along the outer tub walls and around the heater.",
    actions: ["Removed the front panel and door gasket", "Lifted the outer tub out of the frame", "Scrubbed off the deposits, taking care around the heater assembly", "Reassembled, levelled and checked for leaks"],
    result: "After cleaning, the deposits on the tub walls and around the heater had been removed.",
    recorded: "2026",
    sourceNote: "The before and after photos were checked and confirmed to be the same machine and the same job.",
    lesson: [
      { t: "Three places odours like to live in a front loader", d: "The groove behind the door gasket, the outer surface of the inner drum, and the drain pump filter. Water can sit in all three, and the tub-clean programme can't reach them. A clean that really works has to open up all three." },
      { t: "Scale around the heater increases power use", d: "Many front-load models have a water heater under the tub. When scale and deposits build up on it, heat passes into the water more slowly, so the machine takes longer to bring the water up to the set temperature." },
      { t: "What you can do yourself every week", d: "Leave the door open to dry after each wash, and wipe the door gasket groove dry once a week. These two habits genuinely extend the time before the next strip-down clean is due." },
    ],
    alts: ["Washing machine cleaning, before cleaning, photo 1", "Washing machine cleaning, after cleaning, photo 1"],
  },
  "wall-air-filter-heavy-dust": {
    title: "Cleaning an aircon condenser with dust built up along its cooling fins",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Aircon condenser (outdoor coil)",
    reportedIssue: "No symptoms were recorded from the customer, so we do not state that the aircon was not cooling or was using too much power.",
    finding: "The condenser's cooling fins had grey dust built up across the whole surface and between the fins.",
    actions: ["Inspected the condition of the condenser fins", "Brushed and rinsed the dust out along the fins", "Checked the airflow path around the condensing unit"],
    result: "The dust stuck to the condenser fins was cleaned off, leaving a cleaner surface for releasing heat.",
    recorded: "2026",
    sourceNote: "Reported from a single before photo; not paired with photos from any other job.",
    lesson: [
      { t: "Dust on condenser fins isn't only on the surface", d: "The grey you can see on the panel is only the outermost layer. The dust that really makes heat release worse is packed deep between the fins, where you can't see it from outside. A broom or a cloth only cleans the face of the panel; water has to be sprayed from the inside outwards to carry the packed dust out." },
      { t: "Something you can go and check yourself", d: "Stand about an arm's length from the condenser and look into the fins at an angle. If you can still see lines of gaps between the fins, there is still some airflow. If the whole panel looks like a solid, even sheet of grey, dust has clogged it completely." },
      { t: "Why a dirty condenser raises your power bill", d: "The condenser's job is to release heat into the outside air. When the fins are clogged, less heat can escape, so the compressor has to run longer to keep the room as cool as before. That's why I open up and check the condenser every time I come to clean, not just the unit in the room." },
    ],
    alts: ["Aircon cleaning, before cleaning, photo 1"],
  },
  "wall-air-evaporator-dark-deposit": {
    title: "Spray-washing the evaporator coil of a wall-mounted aircon",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Wall-mounted aircon, brand and BTU not visible",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "The evaporator coil cover was opened and cleaning solution was sprayed along the full run of the fins, with a tarp catching the water underneath.",
    actions: ["Opened the cover to reach the coil", "Covered the area and fitted a tarp to catch water", "Spray-washed the coil fins along their length"],
    result: "The evaporator coil was spray-washed across its whole surface, with the water kept under control during the work so it did not spread around the room.",
    recorded: "2026",
    sourceNote: "All information comes from what is visible in the photo.",
    lesson: [
      { t: "Why a tarp goes down before every spray", d: "The water that runs out of the evaporator coil during cleaning isn't plain water; it carries dissolved dust and grime. If it drips onto a wooden floor or curtains, it leaves marks. The tarp and catch bag aren't extras; they are the first step of any cleaning job in a furnished room." },
      { t: "The run-off water tells you whether the cleaning is done", d: "At first the water coming out of the tray is cloudy grey or brown. As the spraying continues, the colour fades until it runs clear. The point where the water runs clear is the point where the coil fins are clean. If a technician packs up while the water is still cloudy, there is still grime left in the coil." },
      { t: "When you can ask to see the work", d: "You can ask to see the condition of the fins before work starts, and again when the rinse water is running out. These are the two moments that show the quality of the job most clearly, with no technical knowledge needed." },
    ],
    alts: ["Aircon cleaning, during cleaning, photo 1"],
  },
  "air-drain-hose-sediment": {
    title: "Sediment built up at the end of an aircon drain hose",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Drain hose of a wall-mounted aircon",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "The end of the drain hose coming out of the unit had brown sediment clinging around its inside wall. This hose is the only way out for the water from the evaporator coil.",
    actions: ["Disconnected the end of the drain hose to inspect it", "Flushed the sediment out of the drain hose", "Reconnected it and checked that water drains out"],
    result: "The sediment was flushed out of the drain hose before it was reconnected.",
    recorded: "2026",
    sourceNote: "Reported from a single photo of the drain hose end; symptoms are not inferred on the customer's behalf.",
    lesson: [
      { t: "A blocked drain hose makes water drip from the front of the unit", d: "Condensate from the evaporator coil runs into the drain tray and out through a single drain hose. When sediment builds up and narrows the hose, water overflows the tray and drips down the front of the unit. Often it isn't a leaking unit at all, just a blocked drain." },
      { t: "Where the sediment in the hose comes from", d: "Dust that slips past the filter and settles on the evaporator coil is washed down by condensate every day. Mixed with moisture, it turns into a slimy film on the hose wall. The longer the gap between cleans, the thicker the sediment gets." },
      { t: "What you can watch for yourself", d: "Look at the end of the drain hose outside while the aircon is running. If water drips out steadily, the drain is still flowing. If the aircon has been on for a long time and the hose end is dry, but water is seeping out at the front of the unit, have a technician check the drain." },
    ],
    alts: ["Aircon cleaning, during cleaning, photo 1"],
  },
  "standard-air-wash-room-protection": {
    title: "Cleaning a wall-mounted aircon with a tarp laid to protect the room",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Wall-mounted aircon indoors, brand and BTU not visible",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "Cleaning in a furnished room means guarding against splashes before the front cover even comes off, so I always start by laying a tarp over the area under the unit.",
    actions: ["Laid a tarp under the unit to catch water", "Removed the front cover and filters", "Spray-washed with the water directed into the catch bag"],
    result: "The area under the unit was covered and protected, and the rinse water was collected straight into the catch bag.",
    recorded: "2026",
    sourceNote: "Uses real photos of the work steps; no claims are made about results outside the frame.",
    lesson: [
      { t: "A furnished room needs protecting before the cover comes off", d: "The riskiest moment when cleaning in a bedroom or living room is removing the front cover, because dust sitting in the tray falls out before any water starts to flow. So I finish covering the area under the unit before I touch it, not when I'm about to start spraying." },
      { t: "How far the catch bag needs to reach", d: "A bag that only sits under the unit isn't enough, because water sprays out sideways under pressure. The bag actually used has to wrap around the unit and channel the water into a bucket through a single outlet." },
      { t: "How you can help before the technician arrives", d: "Move anything you don't want to get wet about an arm's length away from under the unit, and leave room to set up a ladder. This helps the job finish faster and more safely." },
    ],
    alts: ["Aircon cleaning, during cleaning, photo 1"],
  },
  "outdoor-condenser-pressure-wash": {
    title: "Servicing a Panasonic outdoor unit in a tight installation space",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Panasonic condenser (outdoor unit) installed outside the building",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "The Panasonic outdoor unit is installed tucked into a recess on the outside of the building, so the working position had to be set up with care.",
    actions: ["Prepared access to the outdoor unit", "Opened up and inspected the outdoor unit in its installed position", "Checked the unit's condition and mounting points during the work"],
    result: "I reached the outdoor unit in the confined space and inspected it right where it is installed, without having to move any other unit.",
    recorded: "2026",
    sourceNote: "We do not use words like 'colder' or 'saves power' when there are no measurements.",
    lesson: [
      { t: "A condenser must be sprayed from the inside out", d: "Spraying from the outside in pushes the packed dust even deeper and turns it into mud stuck in the middle of the coil. The right direction is from inside the unit outwards, driving the dust back out the way it came in." },
      { t: "Aluminium fins bend more easily than you'd think", d: "Cooling fins are very thin and bend instantly under water pressure or a hand. Flattened fins block the airflow permanently until they are combed straight again. Holding a high-pressure washer too close therefore makes things worse instead of better." },
      { t: "Installation position matters as much as cleanliness", d: "A condenser placed against a wall or in a narrow recess draws back in the hot air it has just blown out. A unit installed like this may still not cool fully even after cleaning. If I find this, I'll let you know, along with options for repositioning it." },
    ],
    alts: ["Aircon cleaning, during cleaning, photo 1"],
  },
  "wall-air-blower-dust": {
    title: "Inspecting a wall-mounted aircon blower wheel with dust along its blades",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Blower wheel of a wall-mounted aircon",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "The inner blades of the blower wheel had dust clinging continuously along their length, a spot that sits deeper than the front cover and filters.",
    actions: ["Opened the front cover to reach the blower assembly", "Checked the dust along the blades", "Spray-washed along the blower wheel with the water caught underneath"],
    result: "I cleaned right down to the inner blades of the blower wheel, a layer that sits deeper than the front cover and filters.",
    recorded: "2026",
    sourceNote: "Only the before-work condition that could be inspected is stated.",
    lesson: [
      { t: "The blower wheel is where dust hides deepest", d: "The blower wheel sits behind the evaporator coil and is barely visible from the front of the unit. Dust that slips past the filters gradually builds up on the blades into a layer, so the airflow gets weaker even when the filters are clean." },
      { t: "Standard and strip-down cleans differ at the blower wheel", d: "A standard clean spray-washes the blower wheel while it is still in the unit, while a strip-down clean takes it out and washes it separately. If the grime on the blades isn't thick yet and there's no odour, a standard clean is enough. I assess this before starting every job." },
      { t: "Why it's better to clean before the smell starts", d: "Once you can smell it, moisture and dust have already built up into grime in the drain tray or the blower, which takes longer to clean than a routine service. Discolouration along the edge of the louvres is a sign you can see before any smell appears." },
    ],
    alts: ["Aircon cleaning, before cleaning, photo 1"],
  },
  "air-drain-tray-clean-result": {
    title: "Plastic parts from a wall-mounted aircon after being washed separately",
    service: "Aircon cleaning",
    area: "Chiang Mai",
    equipment: "Plastic parts from inside a wall-mounted aircon",
    reportedIssue: "No symptoms were recorded from the customer.",
    finding: "The plastic parts were removed and washed separately from the unit, so every groove and edge could be reached properly.",
    actions: ["Removed the parts from the unit", "Washed along the grooves and edges from end to end", "Laid them out to check they were clean before refitting"],
    result: "After washing, the parts were clean along their whole length and were checked before being refitted to the unit.",
    recorded: "2026",
    sourceNote: "Not paired with photos of trays from other jobs to create a fake before/after.",
    lesson: [
      { t: "The drain tray is where musty smells start", d: "Condensate from the evaporator coil flows through the drain tray the whole time the aircon is running. When dust falls in and mixes with it, it becomes a slimy film that is a source of odour. Most of the musty smell that comes out with the cold air comes from here, not from the filters." },
      { t: "A blocked drain makes water drip from the front of the unit", d: "When grime builds up in the tray and blocks the outlet, water overflows the edge of the tray and drips out the front. Homeowners often think the unit is leaking, but it is actually a blocked drain, which cleaning fixes, not replacing parts." },
      { t: "What you should see after cleaning", d: "A cleaned tray should show its original plastic surface all over, with the drain hole clearly open. If there are still streaks of grime along the edges, it was only cleaned on the surface." },
    ],
    alts: ["Aircon cleaning, after cleaning, photo 1"],
  },
  "air-pipe-cover-routing": {
    title: "Aircon pipe routing and trunking run flush along the wall",
    service: "Aircon installation",
    area: "Chiang Mai",
    equipment: "Aircon piping; unit brand and BTU not visible",
    reportedIssue: "Installation job; no additional requirements from the customer were recorded.",
    finding: "The refrigerant lines were insulated and laid inside trunking along the wall.",
    actions: ["Insulated the refrigerant lines", "Bundled the pipes and cables together", "Fitted trunking along the wall"],
    result: "After installation the trunking runs continuously and flush with the wall, keeping the refrigerant lines, insulation and power cable neat.",
    recorded: "2026",
    sourceNote: "Reports only the visible quality of the pipe run.",
    lesson: [
      { t: "Trunking protects the insulation", d: "Insulated refrigerant lines left exposed to the sun deteriorate quickly. The insulation turns brittle and cracks, causing water droplets along the pipe and cooling loss along the way. So the trunking's main job is to shield the insulation from sun and rain; the tidy look is a side benefit." },
      { t: "What a good pipe run looks like", d: "Pipes should run in straight lines, bend only where necessary, and have no spots squeezed flat, because every kink is a point where refrigerant flows less easily and a likely leak point in the future." },
      { t: "The drain hose must slope down all the way", d: "The drain hose relies on gravity alone. If any section rises or runs level, water pools there and flows back. You can check this by eye from outside the house, without switching the unit on." },
    ],
    alts: ["Aircon installation, after installation, photo 1"],
  },
  "sansai-lg-topload-2569-08": {
    title: "LG top-load washing machine strip-down clean in San Sai: rust over the whole stainless steel tub",
    service: "Washing machine cleaning",
    area: "San Sai, Chiang Mai",
    equipment: "LG top-load washing machine, TurboDrum model",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "With the inner tub taken out, brown rust was found on almost the entire outer surface of the stainless steel tub. The base under the pulsator and the water-push rod had built-up black deposits, and the outer tub walls were brown with deposits right down to the bottom of the tub.",
    actions: ["Test-ran the machine before dismantling", "Removed the pulsator, inner tub and filter assembly to wash separately", "Scrubbed rust and deposits off the outside of the stainless steel tub", "Cleaned the outer tub down to the bottom, plus the water-push rod", "Reassembled, levelled and ran a test cycle"],
    result: "The stainless steel tub is shiny again, and no brown deposits are left visible on the pulsator or the bottom of the outer tub.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, during cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
    ],
  },
  "hangdong-hitachi-topload-2569-08": {
    title: "Hitachi top-load washing machine strip-down clean in Hang Dong: thick scale on the pulsator base",
    service: "Washing machine cleaning",
    area: "Hang Dong, Chiang Mai",
    equipment: "Hitachi top-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The bottom of the outer tub was covered in brown deposits, the back of the pulsator had black grime in every groove between its ribs, and the pulsator mounting base had scale built up so thick it had formed lumps.",
    actions: ["Test-ran the machine before dismantling", "Removed the pulsator, inner tub and every other part, laying them out in order on a tarp", "Scrubbed the scale off the pulsator base and out of the grooves between the ribs", "Cleaned the outer tub down to the bottom", "Reassembled, levelled and ran a test cycle"],
    result: "The pulsator and the bottom of the outer tub are clean and white again; every part was cleaned and all of them were refitted.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, during cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
    ],
  },
  "lg-frontload-2569-08": {
    title: "LG front-load washing machine strip-down clean: rust over the whole outside of the stainless steel drum",
    service: "Washing machine cleaning",
    area: "Chiang Mai",
    equipment: "LG front-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The outside of the stainless steel drum, which can't be seen during normal use, was brown with rust all over. The drum spider arms, the detergent drawer and the outer tub walls had built-up brown deposits and mould.",
    actions: ["Test-ran the machine before dismantling", "Removed the front panel and door gasket, and lifted the outer tub out of the frame", "Lifted out the stainless steel drum and scrubbed the rust off its entire outer surface", "Cleaned the detergent drawer, outer tub and drain hose", "Reassembled, levelled and ran a leak test"],
    result: "The stainless steel drum is shiny again inside and out, and the outer tub and door gasket are clean.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page; the post did not state the area.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 5",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 4",
    ],
  },
  "mueang-haier-topload-2569-08": {
    title: "Haier top-load washing machine strip-down clean in Mueang Chiang Mai: pulsator black all over",
    service: "Washing machine cleaning",
    area: "Mueang Chiang Mai",
    equipment: "Haier top-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The back and underside of the pulsator had black deposits so thick they hid its original colour. Half of the stainless steel tub's outer surface had brown rust, and the bottom of the outer tub and the lint filter had built-up brown deposits.",
    actions: ["Test-ran the machine before dismantling", "Removed the pulsator, inner tub and filter assembly to wash separately", "Scrubbed the black deposits off the back of the pulsator and the rust off the outside of the tub", "Cleaned the bottom of the outer tub and the filter assembly", "Reassembled, levelled and ran a test cycle"],
    result: "The pulsator is back to its original blue, the stainless steel tub is shiny, and the bottom of the outer tub and the filter assembly are clean.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, during cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 5",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 4",
    ],
  },
  "maejo-samsung-topload-2569-08": {
    title: "Samsung top-load washing machine strip-down clean in Mae Jo: rust on the pulsator and tub",
    service: "Washing machine cleaning",
    area: "Mae Jo, San Sai, Chiang Mai",
    equipment: "Samsung top-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The back of the pulsator and its mounting base were brown with rust across the whole piece, the outside of the stainless steel tub had bands of rust, and the lint filter and the inside of the tub had built-up deposits.",
    actions: ["Test-ran the machine before dismantling", "Removed the pulsator, inner tub and filter assembly to wash separately", "Scrubbed the rust off the pulsator base and the outside of the tub", "Cleaned the inside of the tub and the filter assembly", "Reassembled, levelled and ran a test cycle"],
    result: "The stainless steel tub and the pulsator base are shiny again, and the inside of the tub is clean, with the blue pulsator clearly visible.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 5",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 6",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
    ],
  },
  "padaet-topload-2569-08": {
    title: "Top-load washing machine strip-down clean in Pa Daet: rust on the outside of the tub and deposits under the pulsator",
    service: "Washing machine cleaning",
    area: "Pa Daet, Mueang Chiang Mai",
    equipment: "Top-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "Half of the stainless steel tub's outer surface had streaks of brown rust, the bottom of the outer tub had dark brown deposits, and the base under the pulsator had black deposits built up around the shaft.",
    actions: ["Test-ran the machine before dismantling", "Lifted out the inner tub and scrubbed the rust off its outer surface", "Removed the pulsator and cleaned its base and the centre shaft", "Cleaned the bottom of the outer tub", "Reassembled, levelled and ran a test cycle"],
    result: "The outside of the stainless steel tub is shiny again, and the bottom of the outer tub is clean with no brown deposits left.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
    ],
  },
  "hangdong-electrolux-frontload-2569-07": {
    title: "Electrolux front-load washing machine strip-down clean in Hang Dong: scale in the outer tub and detergent drawer",
    service: "Washing machine cleaning",
    area: "Hang Dong, Chiang Mai",
    equipment: "Electrolux front-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "Inside the outer tub, brown scale had built up around the door gasket and on the bottom of the tub. The detergent drawer had black deposits, and the drum spider arms and the drain pump filter had built-up brown deposits.",
    actions: ["Test-ran the machine before dismantling", "Removed the front panel and detergent drawer, and lifted the outer tub out of the frame", "Lifted out the stainless steel drum to clean it separately", "Scrubbed the scale out of the outer tub and off the gasket, and cleaned the drain pump filter", "Reassembled, levelled and ran a leak test"],
    result: "The outer tub and the stainless steel drum are clean again, and no deposits are left in the detergent drawer or the filter.",
    recorded: "11 Jul 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 2",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 3",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 4",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 5",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 6",
      "Washing machine cleaning, 11 July 2026, after cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, during cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, after cleaning, photo 2",
    ],
  },
  "topload-2569-07": {
    title: "Top-load washing machine strip-down clean: rusted stainless steel tub and clogged filter",
    service: "Washing machine cleaning",
    area: "Chiang Mai",
    equipment: "Top-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The outside of the stainless steel tub was brown with rust all over, the lint filter was clogged with lint and black deposits, and the filter cover and the parts around the tub had brown deposits on them.",
    actions: ["Test-ran the machine before dismantling", "Lifted out the inner tub and scrubbed the rust off its outer surface", "Removed the pulsator, filter assembly and every other part to wash separately", "Cleaned the outer tub and the tub rim", "Reassembled, levelled and ran a test cycle"],
    result: "The pulsator, tub rim and parts are clean again, and everything was refitted, ready for use.",
    recorded: "11 Jul 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page; the post did not state the area.",
    alts: [
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 2",
      "Washing machine cleaning, 11 July 2026, before cleaning, photo 3",
      "Washing machine cleaning, 11 July 2026, during cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, after cleaning, photo 1",
      "Washing machine cleaning, 11 July 2026, after cleaning, photo 2",
      "Washing machine cleaning, 11 July 2026, after cleaning, photo 3",
    ],
  },
  "mueang-lg-frontload-2569-08": {
    title: "LG front-load washing machine strip-down clean in Mueang Chiang Mai: rusted drum spider and clogged drain hose",
    service: "Washing machine cleaning",
    area: "Mueang Chiang Mai",
    equipment: "LG front-load washing machine",
    reportedIssue: "No customer-reported symptoms were recorded in the post.",
    finding: "The three-arm drum spider on the back of the stainless steel drum was heavily rusted, the outside of the drum had black deposits all over, the outer tub and the door gasket had brown scale, and the detergent drawer and drain hose were clogged inside with black deposits.",
    actions: ["Test-ran the machine before dismantling", "Removed the front panel and detergent drawer, and lifted the outer tub out of the frame", "Lifted out the stainless steel drum and scrubbed the rust off the spider arms and outer surface", "Cleaned the outer tub, door gasket, detergent drawer and drain hose", "Reassembled, levelled and ran a leak test"],
    result: "The stainless steel drum is shiny again inside and out, and the outer tub, gasket and detergent drawer are clean with no deposits left.",
    recorded: "24 Aug 2026",
    sourceNote: "All photos come from the same post on our washing machine cleaning page and show the same machine throughout.",
    alts: [
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 1",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 5",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 6",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 7",
      "Washing machine cleaning, 24 August 2026, before cleaning, photo 8",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 2",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 3",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 4",
      "Washing machine cleaning, 24 August 2026, after cleaning, photo 5",
    ],
  },
};
